services:
    webref:
        image: webref
        build: .
        ports:
            - "7000:80"
        volumes:
            - <path to JabRef's General File Directory>:/webapp/references
        secrets:
            - sqlusername
            - sqlpassword
            - sqlserver
            - sqldatabasename
secrets:
    sqlusername:
        file: ./secrets/sqlusername
    sqlpassword:
        file: ./secrets/sqlpassword
    sqlserver:
        file: ./secrets/sqlserver
    sqldatabasename:
        file: ./secrets/sqldatabasename
